default: &default
  adapter: <%= ENV["ADAPTER"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  
production:
  <<: *default
  database: <%= ENV["DATABASE"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE"] %>

test:
  <<: *default
  database: <%= ENV["DATABASE"] %>
