default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5
  
production:
  <<: *default
  database: <%= ENV['DATABASE'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE'] %>
