default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 5

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
