default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: 'postgres'
  password: 'mypswd'
  pool: 5

production:
  <<: *default
  database: 'postgres'
