name: Build and Deploy gifmachine App with Terraform

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: gifmachine
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U runner"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_ADAPTER: ${{ secrets.DB_ADAPTER }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST:  ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DATABASE }}
      RACK_ENV: ${{ secrets.RACK_ENV }}
          
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Install dependencies
        working-directory: gifmachine
        run: bundle install

      - name: Setup database
        working-directory: gifmachine
        run: |
          bundle exec rake db:migrate

  terraform:
    name: Deploy AWS Infra with Terraform
    runs-on: ubuntu-latest
    environment: gifmachine
    env:
      DB_ADAPTER: postgresql

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: terraform   # path where your .tf files are

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

  containerize:
    runs-on: ubuntu-latest
    environment: gifmachine

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          POSTGRES_DB: gifmachine_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U runner"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image and push to ecr
        working-directory: gifmachine
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t gifmachine:$IMAGE_TAG .
